version: '3'
services:
  influxdb:
    image: influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=your_username
      - DOCKER_INFLUXDB_INIT_PASSWORD=your_password
      - DOCKER_INFLUXDB_INIT_ORG=server_stat
      - DOCKER_INFLUXDB_INIT_BUCKET=Server_Stats
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=F563snz6Ha80Y2pxMHU-6yVonlIrUs-JmhVPVJYY_e4VgwXWq34EtSx5MNES-Lubnz-D7-Kfa8Rlb3gH8aLmRQ==
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"  # Exposes InfluxDB UI on the host
    networks:
      - resourceradar-network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=POSTGRESSECURE
      - POSTGRES_DB=sshinfo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - resourceradar-network
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - resourceradar-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - resourceradar-network
    restart: unless-stopped

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        cub kafka-ready -b kafka:29092 1 120 &&
        echo 'Creating topics...' &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic cpu-metrics --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic memory-metrics --partitions 1 --replication-factor 1 &&
        echo 'Successfully created the following topics:' &&
        kafka-topics --bootstrap-server kafka:29092 --list
      "
    networks:
      - resourceradar-network
    restart: on-failure

  backend:
    image: prajitviswanadha/resourceradar-backend:latest
    ports:
      - "3001:3001"
    environment:
      - INFLUX_TOKEN=F563snz6Ha80Y2pxMHU-6yVonlIrUs-JmhVPVJYY_e4VgwXWq34EtSx5MNES-Lubnz-D7-Kfa8Rlb3gH8aLmRQ==
      - INFLUX_ORG=server_stat
      - INFLUX_BUCKET=Server_Stats
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=sshinfo
      - PGPASSWORD=POSTGRESSECURE
      - PGPORT=5432
      - INFLUXDB_URL=http://influxdb:8086/
      - KAFKA_BROKERS=kafka:29092
    networks:
      - resourceradar-network
      - local_net
    depends_on:
      - influxdb
      - postgres
      - kafka
      - kafka-setup
    restart: unless-stopped

  frontend:
    image: prajitviswanadha/resourceradar-frontend:latest
    ports:
      - "3000:80" 
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - resourceradar-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Exposes Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - influxdb
    networks:
      - resourceradar-network
    restart: unless-stopped

networks:
  resourceradar-network:
    driver: bridge

  # Macvlan network for local network access – update these settings based on your Fedora laptop:
  local_net:
    driver: macvlan
    driver_opts:
      parent: wlp1s0  # Use your wireless interface as listed in ip addr
    ipam:
      config:
        - subnet: 10.184.136.0/23
          gateway: 10.184.136.1
volumes:
  influxdb-data:
  postgres-data:
