version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=your_username
      - DOCKER_INFLUXDB_INIT_PASSWORD=your_password
      - DOCKER_INFLUXDB_INIT_ORG=server_stat
      - DOCKER_INFLUXDB_INIT_BUCKET=Server_Stats
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=F563snz6Ha80Y2pxMHU-6yVonlIrUs-JmhVPVJYY_e4VgwXWq34EtSx5MNES-Lubnz-D7-Kfa8Rlb3gH8aLmRQ==
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - resourceradar-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=POSTGRESSECURE
      - POSTGRES_DB=sshinfo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - resourceradar-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - resourceradar-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - resourceradar-network

  backend:
    image: prajitviswanadha/resourceradar-backend:latest
    environment:
      - INFLUX_TOKEN=F563snz6Ha80Y2pxMHU-6yVonlIrUs-JmhVPVJYY_e4VgwXWq34EtSx5MNES-Lubnz-D7-Kfa8Rlb3gH8aLmRQ==
      - INFLUX_ORG=server_stat
      - INFLUX_BUCKET=Server_Stats
      - PGUSER=postgres
      - PGHOST=localhost
      - PGDATABASE=sshinfo
      - PGPASSWORD=POSTGRESSECURE
      - PGPORT=5432
      - INFLUXDB_URL=http://localhost:8086/
      - KAFKA_BROKERS=localhost:29092
    network_mode: "host"  # Use host network to access all networks the host can access
    depends_on:
      - influxdb
      - postgres
      - kafka

  frontend:
    image: prajitviswanadha/resourceradar-frontend:latest
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=
    networks:
      - resourceradar-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"      # Frontend
      - "8086:8086"  # InfluxDB UI
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - influxdb
    networks:
      - resourceradar-network

networks:
  resourceradar-network:
    driver: bridge

volumes:
  influxdb-data: